[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:php-fpm]
command = /usr/local/sbin/php-fpm
autostart = true
autorestart = true
stdout_logfile = /var/log/php-fpm.log
stdout_logfile_maxbytes = 10485760
stdout_logfile_backups = 10
stderr_logfile = /var/log/php-fpm-error.log
stderr_logfile_maxbytes = 10485760
stderr_logfile_backups = 10

[program:nginx]
command = /usr/sbin/nginx -g "daemon off;"
autostart = true
autorestart = true
stdout_logfile = /var/log/nginx.log
stdout_logfile_maxbytes = 10485760
stdout_logfile_backups = 10
stderr_logfile = /var/log/nginx-error.log
stderr_logfile_maxbytes = 10485760
stderr_logfile_backups = 10
